### ISSUE TITLE
Redundancy

### ISSUE THREAD

**Issue by setare92-ha** [learn-co-curriculum/dsc-github-ssh-guide#1]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for reaching out regarding an issue with this repo. May you give some detail on what the "redundancy" is? Again, appreciate it.

**Comment by setare92-ha** [comment]
Hi,

On Canvas, the same set of course material for using ssh keys appears more
than once (even more than twice I believe). The entire lesson basically
with the exact same text shows up multiple times on the lesson’s page as
you scroll.

Best,
Setare

**Comment by bpurdy-ds** [comment]
If it seems that way, it is since a number of students often have difficulty with setting this up. Thank you again.
