### ISSUE TITLE
SSH Key - GitHub

### ISSUE THREAD

**Issue by Pattycookie** [learn-co-curriculum/dsc-github-ssh-guide#2]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [x] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

## Any Additional Context?
 Having trouble with the SSH Key.

**Comment by Pattycookie** [comment]
I don't have the technical jargon to explain the issue.

**Comment by bpurdy-ds** [comment]
Please reach out to your instructor directly, and then you can also give more details here. But your instructor should be able to help you resolve the issue.
